# name: Deploy to EC2

# on:
#   push:
#     branches: [ "main" ]   
#   workflow_dispatch:       

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4


#       - name: Upload files to EC2
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           source: "."
#           target: "/home/ubuntu/db"
#           overwrite: true
#           rm: true
#           strip_components: 0

#           exclude: |
#             .git
#             .github
#             .venv
#             __pycache__


#       - name: Install deps & restart service
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script_stop: true
#           script: |
#             set -euo pipefail
#             cd /home/ubuntu/db
#             # venv
#             python3 -m venv .venv || true
#             . .venv/bin/activate
#             pip install --upgrade pip
#             pip install -r requirements.txt
#             sudo systemctl daemon-reload
#             sudo systemctl restart dbapp
#             sudo systemctl --no-pager status dbapp | tail -n 50
